[2023-10-24T15:37:50.053+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.extract_data manual__2023-10-24T15:37:37.088067+00:00 [queued]>
[2023-10-24T15:37:50.077+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.extract_data manual__2023-10-24T15:37:37.088067+00:00 [queued]>
[2023-10-24T15:37:50.079+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 3
[2023-10-24T15:37:50.123+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): extract_data> on 2023-10-24 15:37:37.088067+00:00
[2023-10-24T15:37:50.148+0000] {standard_task_runner.py:57} INFO - Started process 629 to run task
[2023-10-24T15:37:50.156+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'extract_data', 'manual__2023-10-24T15:37:37.088067+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/tugaskel8_dag.py', '--cfg-path', '/tmp/tmpzijbhygw']
[2023-10-24T15:37:50.164+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask extract_data
[2023-10-24T15:37:50.279+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_dag.extract_data manual__2023-10-24T15:37:37.088067+00:00 [running]> on host 5628b0258ab1
[2023-10-24T15:37:50.467+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kel8' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2023-10-24T15:37:37.088067+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-24T15:37:37.088067+00:00'
[2023-10-24T15:37:52.189+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tugaskel8_dag.py", line 27, in extract_data
    response = response['results']
TypeError: 'Response' object is not subscriptable
[2023-10-24T15:37:52.221+0000] {taskinstance.py:1398} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_dag, task_id=extract_data, execution_date=20231024T153737, start_date=20231024T153750, end_date=20231024T153752
[2023-10-24T15:37:52.258+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 6 for task extract_data ('Response' object is not subscriptable; 629)
[2023-10-24T15:37:52.311+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-24T15:37:52.346+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
