[2023-10-26T04:38:01.309+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.extract_data manual__2023-10-26T04:37:59.420760+00:00 [queued]>
[2023-10-26T04:38:01.323+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.extract_data manual__2023-10-26T04:37:59.420760+00:00 [queued]>
[2023-10-26T04:38:01.324+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 3
[2023-10-26T04:38:01.343+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): extract_data> on 2023-10-26 04:37:59.420760+00:00
[2023-10-26T04:38:01.353+0000] {standard_task_runner.py:57} INFO - Started process 1270 to run task
[2023-10-26T04:38:01.356+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'extract_data', 'manual__2023-10-26T04:37:59.420760+00:00', '--job-id', '215', '--raw', '--subdir', 'DAGS_FOLDER/tugaskel8_dag.py', '--cfg-path', '/tmp/tmprkd4fgg5']
[2023-10-26T04:38:01.359+0000] {standard_task_runner.py:85} INFO - Job 215: Subtask extract_data
[2023-10-26T04:38:01.423+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_dag.extract_data manual__2023-10-26T04:37:59.420760+00:00 [running]> on host d73c1ff20372
[2023-10-26T04:38:01.732+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kel8' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2023-10-26T04:37:59.420760+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-26T04:37:59.420760+00:00'
[2023-10-26T04:38:01.937+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-10-26T04:38:01.948+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=etl_dag, task_id=extract_data, execution_date=20231026T043759, start_date=20231026T043801, end_date=20231026T043801
[2023-10-26T04:38:02.011+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-26T04:38:02.035+0000] {dagrun.py:743} ERROR - Failed to get task for ti <TaskInstance: etl_dag.create_air_pollution_table manual__2023-10-26T04:37:59.420760+00:00 [up_for_retry]>. Marking it as removed.
[2023-10-26T04:38:02.052+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
