[2023-10-26T06:19:26.398+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_dag.load_data manual__2023-10-26T06:09:10.652490+00:00 [queued]>
[2023-10-26T06:19:26.414+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_dag.load_data manual__2023-10-26T06:09:10.652490+00:00 [queued]>
[2023-10-26T06:19:26.415+0000] {taskinstance.py:1359} INFO - Starting attempt 3 of 3
[2023-10-26T06:19:26.437+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): load_data> on 2023-10-26 06:09:10.652490+00:00
[2023-10-26T06:19:26.446+0000] {standard_task_runner.py:57} INFO - Started process 2368 to run task
[2023-10-26T06:19:26.449+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_dag', 'load_data', 'manual__2023-10-26T06:09:10.652490+00:00', '--job-id', '397', '--raw', '--subdir', 'DAGS_FOLDER/tugaskel8_dag.py', '--cfg-path', '/tmp/tmpsn18s5n5']
[2023-10-26T06:19:26.452+0000] {standard_task_runner.py:85} INFO - Job 397: Subtask load_data
[2023-10-26T06:19:26.516+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_dag.load_data manual__2023-10-26T06:09:10.652490+00:00 [running]> on host d73c1ff20372
[2023-10-26T06:19:26.937+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kel8' AIRFLOW_CTX_DAG_ID='etl_dag' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2023-10-26T06:09:10.652490+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-26T06:09:10.652490+00:00'
[2023-10-26T06:19:27.097+0000] {base.py:73} INFO - Using connection ID 'db_polusiudara' for task execution.
[2023-10-26T06:19:28.363+0000] {sql.py:418} INFO - Running statement: INSERT INTO hands_on_final (id,city,name,entity,country,sources,isMobile,isAnalysis,sensorType,firstUpdated,lastUpdated,measurements) VALUES (8637, 'Jakarta', 'US Diplomatic Post: Jakarta Central', 'None', 'ID', 'None', False, None, 'None', '2016-11-09T17:00:00+00:00', '2023-10-26T12:00:00+00:00', 60486), parameters: None
[2023-10-26T06:19:28.426+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/tugaskel8_dag.py", line 58, in load_data
    hook.run(f"INSERT INTO hands_on_final (id,city,name,entity,country,sources,isMobile,isAnalysis,sensorType,firstUpdated,lastUpdated,measurements) VALUES ({row['id']}, '{row['city']}', '{row['name']}', '{row['entity']}', '{row['country']}', '{row['sources']}', {row['isMobile']}, {row['isAnalysis']}, '{row['sensorType']}', '{row['firstUpdated']}', '{row['lastUpdated']}', {row['measurements']})")
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 392, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "none" does not exist
LINE 1: ...t: Jakarta Central', 'None', 'ID', 'None', False, None, 'Non...
                                                             ^
HINT:  Perhaps you meant to reference the column "hands_on_final.name".

[2023-10-26T06:19:28.444+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=etl_dag, task_id=load_data, execution_date=20231026T060910, start_date=20231026T061926, end_date=20231026T061928
[2023-10-26T06:19:28.475+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 397 for task load_data (column "none" does not exist
LINE 1: ...t: Jakarta Central', 'None', 'ID', 'None', False, None, 'Non...
                                                             ^
HINT:  Perhaps you meant to reference the column "hands_on_final.name".
; 2368)
[2023-10-26T06:19:28.555+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-26T06:19:28.578+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
